package com.chrrissoft.permissionscompanion.ui.theme

import androidx.compose.ui.graphics.Color


val md_theme_dark_primary = Color(0xFF5ED4FC)
val md_theme_dark_onPrimary = Color(0xFF003544)
val md_theme_dark_primaryContainer = Color(0xFF004D61)
val md_theme_dark_onPrimaryContainer = Color(0xFFB8EAFF)
val md_theme_dark_secondary = Color(0xFFB3CAD5)
val md_theme_dark_onSecondary = Color(0xFF1E333C)
val md_theme_dark_secondaryContainer = Color(0xFF344A53)
val md_theme_dark_onSecondaryContainer = Color(0xFFCFE6F1)
val md_theme_dark_tertiary = Color(0xFFC3C3EB)
val md_theme_dark_onTertiary = Color(0xFF2C2D4D)
val md_theme_dark_tertiaryContainer = Color(0xFF434465)
val md_theme_dark_onTertiaryContainer = Color(0xFFE1E0FF)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF191C1D)
val md_theme_dark_onBackground = Color(0xFFE1E3E4)
val md_theme_dark_surface = Color(0xFF191C1D)
val md_theme_dark_onSurface = Color(0xFFE1E3E4)
val md_theme_dark_surfaceVariant = Color(0xFF40484C)
val md_theme_dark_onSurfaceVariant = Color(0xFFBFC8CC)
val md_theme_dark_outline = Color(0xFF8A9296)
val md_theme_dark_inverseOnSurface = Color(0xFF191C1D)
val md_theme_dark_inverseSurface = Color(0xFFE1E3E4)
val md_theme_dark_inversePrimary = Color(0xFF006780)
val md_theme_dark_surfaceTint = Color(0xFF5ED4FC)
val md_theme_dark_outlineVariant = Color(0xFF40484C)
val md_theme_dark_scrim = Color(0xFF000000)
